name: Ephemeral Runner Only

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  GITHUB_REPO: ilyara-aya-elmafhoum/backend
  SEMAPHORE_URL: http://84.234.24.138:3000
  PROJECT_ID: 1
  CREATE_TEMPLATE_ID: 18
  ANSIBLE_TEMPLATE_ID: 6

jobs:
  # 1. Création de la machine éphémère
  create-runner:
    runs-on: ubuntu-24.04
    outputs:
      create_template_id: ${{ env.CREATE_TEMPLATE_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installer dépendances
        run: |
          sudo apt update && sudo apt install -y jq curl
          chmod +x ./scripts/semaphore_task.sh

      - name: Créer la machine éphémère sur Semaphore
        env:
          SEMAPHORE_TOKEN: ${{ secrets.SEMAPHORE_TOKEN }}
        run: ./scripts/semaphore_task.sh create $CREATE_TEMPLATE_ID

      - name: Générer le token GitHub Runner
        id: generate_token
        run: |
          TOKEN=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GH_PERSONAL_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ env.GITHUB_REPO }}/actions/runners/registration-token" \
            | jq -r '.token')
          echo "GITHUB_RUNNER_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Configurer le runner via Ansible (Semaphore)
        env:
          SEMAPHORE_TOKEN: ${{ secrets.SEMAPHORE_TOKEN }}
          GITHUB_REPO: ${{ env.GITHUB_REPO }}
          GITHUB_RUNNER_TOKEN: ${{ env.GITHUB_RUNNER_TOKEN }}
        run: ./scripts/semaphore_task.sh ansible $ANSIBLE_TEMPLATE_ID

